-- MySQL Script generated by MySQL Workbench
-- Sun Mar 11 20:59:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agomubcz_proxecto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agomubcz_proxecto` ;

-- -----------------------------------------------------
-- Schema agomubcz_proxecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agomubcz_proxecto` DEFAULT CHARACTER SET utf8 ;
USE `agomubcz_proxecto` ;

-- -----------------------------------------------------
-- Table `agomubcz_proxecto`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agomubcz_proxecto`.`usuario` ;

CREATE TABLE IF NOT EXISTS `agomubcz_proxecto`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(45) NOT NULL,
  `contrasinal` VARCHAR(16) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `apelidos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agomubcz_proxecto`.`tenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agomubcz_proxecto`.`tenda` ;

CREATE TABLE IF NOT EXISTS `agomubcz_proxecto`.`tenda` (
  `idtenda` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `enderezo` VARCHAR(45) NULL,
  `codpostal` INT NULL,
  `latitude` INT NULL,
  `lonxitude` INT NULL,
  PRIMARY KEY (`idtenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agomubcz_proxecto`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agomubcz_proxecto`.`producto` ;

CREATE TABLE IF NOT EXISTS `agomubcz_proxecto`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descript` TEXT(100) NULL,
  `urlFoto` VARCHAR(45) NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agomubcz_proxecto`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agomubcz_proxecto`.`comentario` ;

CREATE TABLE IF NOT EXISTS `agomubcz_proxecto`.`comentario` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `texto` TEXT NULL,
  PRIMARY KEY (`idcomentario`, `usuario_idusuario`, `producto_idproducto`),
  INDEX `fk_comentario_usuario_idx` (`usuario_idusuario` ASC),
  INDEX `fk_comentario_producto1_idx` (`producto_idproducto` ASC),
  CONSTRAINT `fk_comentario_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `agomubcz_proxecto`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `agomubcz_proxecto`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agomubcz_proxecto`.`tenda_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agomubcz_proxecto`.`tenda_producto` ;

CREATE TABLE IF NOT EXISTS `agomubcz_proxecto`.`tenda_producto` (
  `tenda_idtenda` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `prezo` DOUBLE NOT NULL,
  PRIMARY KEY (`tenda_idtenda`, `producto_idproducto`),
  INDEX `fk_tenda_has_producto_producto1_idx` (`producto_idproducto` ASC),
  INDEX `fk_tenda_has_producto_tenda1_idx` (`tenda_idtenda` ASC),
  CONSTRAINT `fk_tenda_has_producto_tenda1`
    FOREIGN KEY (`tenda_idtenda`)
    REFERENCES `agomubcz_proxecto`.`tenda` (`idtenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tenda_has_producto_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `agomubcz_proxecto`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
